### ISSUE TITLE
[Android] Crash Caused by android.database.sqlite.SQLiteException

### ISSUE THREAD

**Issue by youssef-makhoul** [morenoh149/react-native-contacts#508]
I came across a crash on Android while getting contacts on Android 10 as follows:

```
Fatal Exception: java.lang.RuntimeException
An error occurred while executing doInBackground()
android.os.AsyncTask$4.done
_________________________________________________________________________
Caused by android.database.sqlite.SQLiteException
Row too big to fit into CursorWindow requiredPos=3438, totalRows=3439
android.database.DatabaseUtils.readExceptionFromParcel 
android.database.CursorWrapper.moveToNext 
com.rt2zz.reactnativecontacts.ContactsProvider.loadContactsFrom 
com.rt2zz.reactnativecontacts.ContactsProvider.getContactsByPhoneNumber
com.rt2zz.reactnativecontacts.ContactsManager$4.doInBackground 
com.rt2zz.reactnativecontacts.ContactsManager$4.doInBackground
android.os.AsyncTask$3.call 
java.lang.Thread.run
```

it seems that this is either something caused by SQL size restriction on how big a row can be, or a limit on the number of contacts can be fetched per request.

Does anyone have a clue how to solve this crash?

**Comment by markbrown4** [comment]
I've seen this error _once_ as well.  Not sure how to reproduce though.
```
Caused by: android.database.sqlite.SQLiteException: Row too big to fit into CursorWindow requiredPos=189, totalRows=190
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:186)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
at android.database.BulkCursorProxy.getWindow(BulkCursorNative.java:166)
at android.database.BulkCursorToCursorAdaptor.onMove(BulkCursorToCursorAdaptor.java:82)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:255)
at android.database.AbstractCursor.moveToNext(AbstractCursor.java:287)
at android.database.CursorWrapper.moveToNext(CursorWrapper.java:206)
at com.rt2zz.reactnativecontacts.ContactsProvider.loadContactsFrom(ContactsProvider.java:311)
at com.rt2zz.reactnativecontacts.ContactsProvider.getContacts(ContactsProvider.java:287)
at com.rt2zz.reactnativecontacts.ContactsManager$1.doInBackground(ContactsManager.java:96)
at com.rt2zz.reactnativecontacts.ContactsManager$1.doInBackground(ContactsManager.java:89)
at android.os.AsyncTask$3.call(AsyncTask.java:394)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:920)
```

**Comment by morenoh149** [comment]
sorry I have no further insight into this.

**Comment by KonstantinZhukovskij** [comment]
any news here? I got the same error, when i call getAll(). Android api 23

**Comment by KonstantinZhukovskij** [comment]
After some investigation time. Without accepting permissions to read and write the storage, android crashes the application. Check if you have added to the manifest 
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.WRITE_CONTACTS" />
