### ISSUE TITLE
Crash: java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getCount()' on a null object reference

### ISSUE THREAD

**Issue by arjun1194** [morenoh149/react-native-contacts#678]
We are facing this crash 
```
java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getCount()' on a null object reference
    at com.rt2zz.reactnativecontacts.ContactsProvider.getContactsCount(ContactsProvider.java:2)
    at com.rt2zz.reactnativecontacts.ContactsManager$2.doInBackground(ContactsManager.java:5)
    at com.rt2zz.reactnativecontacts.ContactsManager$2.doInBackground(ContactsManager.java:1)
    at android.os.AsyncTask$2.call(AsyncTask.java:292)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
java.lang.RuntimeException: An error occured while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:304)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
    ```

**Comment by arjun1194** [comment]
please Address this Pull request 
https://github.com/morenoh149/react-native-contacts/pull/679

**Comment by anton-patrushev** [comment]
#679 PR was merged AFAICS
@morenoh149 any chances new release would be assembled soon (including this fix)?

**Comment by morenoh149** [comment]
@anton-patrushev yes I'll cut a release
